SELECT
    bm.BANK_NAME,
    bec.ELIGIBLE_SCORE,
    bec.FISCAL_YEAR,
    bec.FIN_PERIOD,
    bec.ELIGIBILITY_ID
FROM BANK_MASTER bm
JOIN BANK_ELIGIBILITY_CRITERIA bec
  ON bm.BANK_ID = bec.BANK_ID
JOIN (
    SELECT BANK_ID, FISCAL_YEAR, MAX(ELIGIBILITY_ID) AS MAX_ID
    FROM BANK_ELIGIBILITY_CRITERIA
    WHERE FISCAL_YEAR = :year
      AND UPPER(TRIM(NVL(ELIGIBLE_SCORE, 'N'))) = 'Y'
    GROUP BY BANK_ID, FISCAL_YEAR
) latest
  ON bec.BANK_ID = latest.BANK_ID
 AND bec.FISCAL_YEAR = latest.FISCAL_YEAR
 AND bec.ELIGIBILITY_ID = latest.MAX_ID
ORDER BY bm.BANK_NAME ASC