SELECT 
    bm.BANK_NAME,
    bec.ELIGIBLE_SCORE,
    bec.FISCAL_YEAR,
    bec.FIN_PERIOD,
    bec.ELIGIBILITY_ID
FROM BANK_MASTER bm
JOIN BANK_ELIGIBILITY_CRITERIA bec ON bm.BANK_ID = bec.BANK_ID
INNER JOIN (
    SELECT BANK_ID, MAX(ELIGIBILITY_ID) as MAX_ID
    FROM BANK_ELIGIBILITY_CRITERIA
    GROUP BY BANK_ID
) latest ON bec.ELIGIBILITY_ID = latest.MAX_ID
WHERE bec.ELIGIBLE_SCORE = 'Y'
ORDER BY bm.BANK_NAME ASC