  CREATE TABLE "BANK_MASTER" 
   (	"BANK_ID" NUMBER, 
	"BANK_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"BANK_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"BANK_TYPE" VARCHAR2(100), 
	"WEBSITE_URL" VARCHAR2(255), 
	"IS_ACTIVE_YN" CHAR(1) DEFAULT 'Y', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	 CHECK (is_active_yn IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("BANK_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("BANK_CODE")
  USING INDEX  ENABLE
   ) ;